version: "3"
services:
  web:
    build: .
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./app:/app
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
