services:
  web:
    build: .
    env_file: .env
    tty: true
    ports:
      - 8002:${SERVER_PORT:-8000}
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:

